# Data science basics

## Numpy

In [1]:
import numpy as np

In [2]:
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])
array


array([1, 2, 3, 4, 5])

In [3]:
# Basic operations
print(array + 5)  # Element-wise addition
print(array * 2)  # Element-wise multiplication


[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [4]:
# Multi-dimensional arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
slice1 = matrix[1:,1:]
slice1

array([[5, 6],
       [8, 9]])

In [18]:
numbers = matrix.reshape((9, ))

In [21]:
numbers[ numbers>2 ]

array([3, 4, 5, 6, 7, 8, 9])

## Pandas

In [12]:
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Department': ['HR', 'IT', 'Finance', 'Marketing']
}
data


{'Name': ['Alice', 'Bob', 'Charlie', 'David'],
 'Age': [25, 30, 35, 40],
 'Department': ['HR', 'IT', 'Finance', 'Marketing']}

In [13]:
df = pd.DataFrame(data)
df


,Name,Age,Department
0,Alice,25,HR
1,Bob,30,IT
2,Charlie,35,Finance
3,David,40,Marketing


### Basic operations

In [15]:
df.describe()

,Age
count,4.000000
mean,32.500000
std,6.454972
min,25.000000
25%,28.750000
50%,32.500000
75%,36.250000
max,40.000000


In [24]:
df[df['Age']>30]

,Name,Age,Department
2,Charlie,35,Finance
3,David,40,Marketing
